apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    purpose: test-secret
spec:
  containers:
  - name: pod-secret
    image: debian
    env: 
    - name: SECRET_VALUE_ENVIRONMENT_DB_HOST
      valueFrom: 
        secretKeyRef: 
          name: secret-file-yaml
          key: DB_HOST
    - name: SECRET_VALUE_ENVIRONMENT_DB_USER
      valueFrom: 
        secretKeyRef: 
          name: secret-file-yaml
          key: DB_USER
    command: ["/bin/echo"]
    args: ["$(SECRET_VALUE_ENVIRONMENT_DB_HOST)", "$(SECRET_VALUE_ENVIRONMENT_DB_USER)"]
  restartPolicy: OnFailure